---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-ttyd-data
  labels:
    app: nanobot-ttyd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-ttyd-workspace
  labels:
    app: nanobot-ttyd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
