# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pytype: skip-file
# pylint: disable=protected-access
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: localharness.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12localharness.proto\x12\x18\x61ntigravity.localharness"W\n\x0bInputConfig\x12\x19\n\x11storage_directory\x18\x01'
    b' \x01(\t\x12\x0c\n\x04port\x18\x02'
    b' \x01(\r\x12\x1f\n\x0c\x62ind_address\x18\x03'
    b' \x01(\t:\tlocalhost"V\n\x1bInitializeConversationEvent\x12\x37\n\x06\x63onfig\x18\x01'
    b' \x01(\x0b\x32\'.antigravity.localharness.HarnessConfig"\xb5\x04\n\rHarnessConfig\x12\x12\n\ncascade_id\x18\x01'
    b' \x01(\t\x12?\n\rgemini_config\x18\x02'
    b' \x01(\x0b\x32&.antigravity.localharness.GeminiConfigH\x00\x12=\n\x0cgemma_config\x18\x03'
    b' \x01(\x0b\x32%.antigravity.localharness.GemmaConfigH\x00\x12I\n\x13system_instructions\x18\x04'
    b' \x01(\x0b\x32,.antigravity.localharness.SystemInstructions\x12-\n\x05tools\x18\x05'
    b' \x03(\x0b\x32\x1e.antigravity.localharness.Tool\x12\x46\n\x12harness_side_tools\x18\x06'
    b' \x01(\x0b\x32*.antigravity.localharness.HarnessSideTools\x12\x1c\n\x14\x63ompaction_threshold\x18\x07'
    b' \x01(\r\x12\x37\n\nworkspaces\x18\x08'
    b' \x03(\x0b\x32#.antigravity.localharness.Workspace\x12\x14\n\x0cskills_paths\x18\t'
    b' \x03(\t\x12\x1f\n\x17\x66inish_tool_schema_json\x18\n'
    b' \x01(\t\x12\x1a\n\x12initial_trajectory\x18\x0b'
    b' \x01(\x0c\x12\x14\n\x0c\x61pp_data_dir\x18\x0c'
    b' \x01(\tB\x0e\n\x0cmodel_config"l\n\tWorkspace\x12M\n\x14\x66ilesystem_workspace\x18\x01'
    b' \x01(\x0b\x32-.antigravity.localharness.FilesystemWorkspaceH\x00\x42\x10\n\x0eworkspace_type"(\n\x13\x46ilesystemWorkspace\x12\x11\n\tdirectory\x18\x01'
    b' \x01(\t"\xa9\x01\n\x0cGeminiConfig\x12\x0f\n\x07\x61pi_key\x18\x01'
    b' \x01(\t\x12\x10\n\x08\x62\x61se_url\x18\x02'
    b' \x01(\t\x12$\n\nmodel_name\x18\x03'
    b' \x01(\t:\x10gemini-3.5-flash\x12\x16\n\x0ethinking_level\x18\x04'
    b' \x01(\t\x12\x1a\n\x12\x65nable_url_context\x18\x05'
    b' \x01(\x08\x12\x1c\n\x14\x65nable_google_search\x18\x06'
    b' \x01(\x08"3\n\x0bGemmaConfig\x12\x10\n\x08\x62\x61se_url\x18\x01'
    b' \x01(\t\x12\x12\n\nmodel_name\x18\x02'
    b' \x01(\t"\xac\x01\n\x12SystemInstructions\x12\x44\n\x06\x63ustom\x18\x01'
    b' \x01(\x0b\x32\x32.antigravity.localharness.CustomSystemInstructionsH\x00\x12H\n\x08\x61ppended\x18\x02'
    b' \x01(\x0b\x32\x34.antigravity.localharness.AppendedSystemInstructionsH\x00\x42\x06\n\x04type"\x81\x01\n\x18\x43ustomSystemInstructions\x12\x45\n\x04part\x18\x01'
    b' \x03(\x0b\x32\x37.antigravity.localharness.CustomSystemInstructions.Part\x1a\x1e\n\x04Part\x12\x0e\n\x04text\x18\x01'
    b' \x01(\tH\x00\x42\x06\n\x04part"\xb9\x01\n\x1a\x41ppendedSystemInstructions\x12\x17\n\x0f\x63ustom_identity\x18\x01'
    b' \x01(\t\x12W\n\x11\x61ppended_sections\x18\x02'
    b' \x03(\x0b\x32<.antigravity.localharness.AppendedSystemInstructions.Section\x1a)\n\x07Section\x12\r\n\x05title\x18\x01'
    b' \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02'
    b' \x01(\t"g\n\x04Tool\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x1e\n\x16parameters_json_schema\x18\x03'
    b' \x01(\t\x12\x1c\n\x14response_json_schema\x18\x04'
    b' \x01(\t"\xef\x05\n\x10HarnessSideTools\x12\x36\n\x04\x66ind\x18\x01'
    b' \x01(\x0b\x32(.antigravity.localharness.FindToolConfig\x12\x43\n\x0brun_command\x18\x02'
    b' \x01(\x0b\x32..antigravity.localharness.RunCommandToolConfig\x12<\n\tsubagents\x18\x03'
    b' \x01(\x0b\x32).antigravity.localharness.SubagentsConfig\x12\x45\n\x0euser_questions\x18\x04'
    b' \x01(\x0b\x32-.antigravity.localharness.UserQuestionsConfig\x12?\n\tfile_edit\x18\x05'
    b' \x01(\x0b\x32,.antigravity.localharness.FileEditToolConfig\x12?\n\tview_file\x18\x06'
    b' \x01(\x0b\x32,.antigravity.localharness.ViewFileToolConfig\x12\x46\n\rwrite_to_file\x18\x07'
    b' \x01(\x0b\x32/.antigravity.localharness.WriteToFileToolConfig\x12\x43\n\x0bgrep_search\x18\x08'
    b' \x01(\x0b\x32..antigravity.localharness.GrepSearchToolConfig\x12=\n\x08list_dir\x18\t'
    b' \x01(\x0b\x32+.antigravity.localharness.ListDirToolConfig\x12@\n\x0bpermissions\x18\n'
    b' \x01(\x0b\x32+.antigravity.localharness.PermissionsConfig\x12I\n\x0egenerate_image\x18\x0b'
    b' \x01(\x0b\x32\x31.antigravity.localharness.GenerateImageToolConfig"\'\n\x0e\x46indToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"-\n\x14RunCommandToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"(\n\x0fSubagentsConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true",\n\x13UserQuestionsConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"+\n\x12\x46ileEditToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"+\n\x12ViewFileToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true".\n\x15WriteToFileToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"-\n\x14GrepSearchToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"*\n\x11ListDirToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"d\n\x17GenerateImageToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true\x12\x32\n\nmodel_name\x18\x02'
    b' \x01(\t:\x1egemini-3.1-flash-image-preview"9\n\x11PermissionsConfig\x12$\n\x1c\x65nforce_workspace_validation\x18\x01'
    b' \x01(\x08"-\n\x0cOutputConfig\x12\x0c\n\x04port\x18\x01'
    b' \x01(\x05\x12\x0f\n\x07\x61pi_key\x18\x02'
    b' \x01(\t"\xcc\x02\n\x0bOutputEvent\x12\x0f\n\x07seq_num\x18\x01'
    b' \x01(\x03\x12\x18\n\x10timestamp_micros\x18\x02'
    b' \x01(\x03\x12;\n\x0bstep_update\x18\n'
    b' \x01(\x0b\x32$.antigravity.localharness.StepUpdateH\x00\x12R\n\x17trajectory_state_update\x18\x0b'
    b' \x01(\x0b\x32/.antigravity.localharness.TrajectoryStateUpdateH\x00\x12\x37\n\ttool_call\x18\x0c'
    b' \x01(\x0b\x32".antigravity.localharness.ToolCallH\x00\x12?\n\x0eusage_metadata\x18\x14'
    b' \x01(\x0b\x32\'.antigravity.localharness.UsageMetadataB\x07\n\x05\x65vent"\xc7\x0c\n\nStepUpdate\x12\x12\n\ncascade_id\x18\x01'
    b' \x01(\t\x12\x15\n\rtrajectory_id\x18\x02'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x03 \x01(\r\x12\x39\n\x05state\x18\x04'
    b' \x01(\x0e\x32*.antigravity.localharness.StepUpdate.State\x12;\n\x06source\x18\x05'
    b' \x01(\x0e\x32+.antigravity.localharness.StepUpdate.Source\x12;\n\x06target\x18\x06'
    b' \x01(\x0e\x32+.antigravity.localharness.StepUpdate.Target\x12\x15\n\rerror_message\x18\x07'
    b' \x01(\t\x12\x10\n\x08thinking\x18\x08'
    b' \x01(\t\x12\x12\n\ntext_delta\x18\t'
    b' \x01(\t\x12\x16\n\x0ethinking_delta\x18\n'
    b' \x01(\t\x12\x0c\n\x04text\x18\x14'
    b' \x01(\t\x12\x45\n\x0elist_directory\x18\x15'
    b' \x01(\x0b\x32-.antigravity.localharness.ActionListDirectory\x12;\n\tfind_file\x18\x16'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionFindFile\x12I\n\x10search_directory\x18\x17'
    b' \x01(\x0b\x32/.antigravity.localharness.ActionSearchDirectory\x12;\n\tview_file\x18\x18'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionViewFile\x12?\n\x0b\x63reate_file\x18\x19'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionCreateFile\x12;\n\tedit_file\x18\x1a'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionEditFile\x12?\n\x0brun_command\x18\x1b'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionRunCommand\x12>\n\ncompaction\x18\x1c'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionCompaction\x12G\n\x0finvoke_subagent\x18\x1d'
    b' \x01(\x0b\x32..antigravity.localharness.ActionInvokeSubagent\x12\x45\n\x0egenerate_image\x18\x1e'
    b' \x01(\x0b\x32-.antigravity.localharness.ActionGenerateImage\x12\x36\n\x06\x66inish\x18\x1f'
    b' \x01(\x0b\x32&.antigravity.localharness.ActionFinish\x12\x34\n\x05\x65rror\x18'
    b'  \x01(\x0b\x32%.antigravity.localharness.ActionError\x12\x14\n\x0crequest_text\x18\x32'
    b' \x01(\t\x12T\n\x19tool_confirmation_request\x18\x33'
    b' \x01(\x0b\x32\x31.antigravity.localharness.ToolConfirmationRequest\x12I\n\x11questions_request\x18\x34'
    b' \x01(\x0b\x32..antigravity.localharness.UserQuestionsRequest"m\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x10\n\x0cSTATE_ACTIVE\x10\x01\x12\x0e\n\nSTATE_DONE\x10\x02\x12\x1a\n\x16STATE_WAITING_FOR_USER\x10\x03\x12\x0f\n\x0bSTATE_ERROR\x10\x04"V\n\x06Source\x12\x16\n\x12SOURCE_UNSPECIFIED\x10\x00\x12\x11\n\rSOURCE_SYSTEM\x10\x01\x12\x0f\n\x0bSOURCE_USER\x10\x02\x12\x10\n\x0cSOURCE_MODEL\x10\x03"[\n\x06Target\x12\x16\n\x12TARGET_UNSPECIFIED\x10\x00\x12\x0f\n\x0bTARGET_USER\x10\x01\x12\x10\n\x0cTARGET_MODEL\x10\x02\x12\x16\n\x12TARGET_ENVIRONMENT\x10\x03"N\n\x13\x41\x63tionGenerateImage\x12\x0e\n\x06prompt\x18\x01'
    b' \x01(\t\x12\x13\n\x0bimage_paths\x18\x02'
    b' \x03(\t\x12\x12\n\nimage_name\x18\x03'
    b' \x01(\t"%\n\x0c\x41\x63tionFinish\x12\x15\n\routput_string\x18\x01'
    b' \x01(\t"7\n\x0b\x41\x63tionError\x12\x15\n\rerror_message\x18\x01'
    b' \x01(\t\x12\x11\n\thttp_code\x18\x02'
    b' \x01(\r"\xc1\x01\n\x13\x41\x63tionListDirectory\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\x45\n\x07results\x18\x02'
    b' \x03(\x0b\x32\x34.antigravity.localharness.ActionListDirectory.Result\x1aK\n\x06Result\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x16\n\x0cis_directory\x18\x02'
    b' \x01(\x08H\x00\x12\x13\n\tfile_size\x18\x03'
    b' \x01(\x04H\x00\x42\x06\n\x04info"G\n\x0e\x41\x63tionFindFile\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03'
    b' \x01(\t"S\n\x15\x41\x63tionSearchDirectory\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\r\n\x05query\x18\x02'
    b' \x01(\t\x12\x13\n\x0bnum_results\x18\x03'
    b' \x01(\x05"I\n\x0e\x41\x63tionViewFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x12\n\nstart_line\x18\x02'
    b' \x01(\r\x12\x10\n\x08\x65nd_line\x18\x03'
    b' \x01(\r"7\n\x10\x41\x63tionCreateFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x10\n\x08\x63ontents\x18\x02'
    b' \x01(\t"\xba\x03\n\x0e\x41\x63tionEditFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x46\n\ndiff_block\x18\x02'
    b' \x03(\x0b\x32\x32.antigravity.localharness.ActionEditFile.DiffBlock\x1a\xd7\x01\n\x08\x44iffLine\x12\x0c\n\x04text\x18\x01'
    b' \x01(\t\x12L\n\x06\x61\x63tion\x18\x02'
    b' \x01(\x0e\x32<.antigravity.localharness.ActionEditFile.DiffLine.LineAction"o\n\nLineAction\x12\x1b\n\x17LINE_ACTION_UNSPECIFIED\x10\x00\x12\x16\n\x12LINE_ACTION_INSERT\x10\x01\x12\x16\n\x12LINE_ACTION_DELETE\x10\x02\x12\x14\n\x10LINE_ACTION_NONE\x10\x03\x1as\n\tDiffBlock\x12\x12\n\nstart_line\x18\x01'
    b' \x01(\x05\x12\x10\n\x08\x65nd_line\x18\x02'
    b' \x01(\x05\x12@\n\x05lines\x18\x03'
    b' \x03(\x0b\x32\x31.antigravity.localharness.ActionEditFile.DiffLine"i\n\x10\x41\x63tionRunCommand\x12\x14\n\x0c\x63ommand_line\x18\x01'
    b' \x01(\t\x12\x13\n\x0bworking_dir\x18\x02'
    b' \x01(\t\x12\x11\n\texit_code\x18\x04'
    b' \x01(\x05\x12\x17\n\x0f\x63ombined_output\x18\x05'
    b' \x01(\t"\x12\n\x10\x41\x63tionCompaction"\x16\n\x14\x41\x63tionInvokeSubagent"\x19\n\x17ToolConfirmationRequest"Q\n\x14UserQuestionsRequest\x12\x39\n\tquestions\x18\x01'
    b' \x03(\x0b\x32&.antigravity.localharness.UserQuestion"d\n\x0cUserQuestion\x12\x43\n\x0fmultiple_choice\x18\x01'
    b' \x01(\x0b\x32(.antigravity.localharness.MultipleChoiceH\x00\x42\x0f\n\rquestion_type"L\n\x0eMultipleChoice\x12\x10\n\x08question\x18\x01'
    b' \x01(\t\x12\x0f\n\x07\x63hoices\x18\x02'
    b' \x03(\t\x12\x17\n\x0fis_multi_select\x18\x03'
    b' \x01(\x08"\xfb\x02\n\nInputEvent\x12\x14\n\nuser_input\x18\x01'
    b' \x01(\tH\x00\x12\x41\n\x12\x63omplex_user_input\x18\x07'
    b' \x01(\x0b\x32#.antigravity.localharness.UserInputH\x00\x12G\n\x11tool_confirmation\x18\x02'
    b' \x01(\x0b\x32*.antigravity.localharness.ToolConfirmationH\x00\x12?\n\rtool_response\x18\x03'
    b' \x01(\x0b\x32&.antigravity.localharness.ToolResponseH\x00\x12L\n\x11question_response\x18\x04'
    b' \x01(\x0b\x32/.antigravity.localharness.UserQuestionsResponseH\x00\x12\x16\n\x0chalt_request\x18\x05'
    b' \x01(\x08H\x00\x12\x1b\n\x11\x61utomated_trigger\x18\x06'
    b' \x01(\tH\x00\x42\x07\n\x05\x65vent"\xdf\x01\n\tUserInput\x12\x37\n\x05parts\x18\x01'
    b' \x03(\x0b\x32(.antigravity.localharness.UserInput.Part\x1a=\n\x05Media\x12\x11\n\tmime_type\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03'
    b' \x01(\x0c\x1aZ\n\x04Part\x12\x0e\n\x04text\x18\x01'
    b' \x01(\tH\x00\x12:\n\x05media\x18\x02'
    b' \x01(\x0b\x32).antigravity.localharness.UserInput.MediaH\x00\x42\x06\n\x04part"O\n\x10ToolConfirmation\x12\x15\n\rtrajectory_id\x18\x01'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x02'
    b' \x01(\r\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x03'
    b' \x01(\x08"\xb7\x01\n\x15TrajectoryStateUpdate\x12\x15\n\rtrajectory_id\x18\x02'
    b' \x01(\t\x12\x44\n\x05state\x18\x03'
    b' \x01(\x0e\x32\x35.antigravity.localharness.TrajectoryStateUpdate.State"A\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n\rSTATE_RUNNING\x10\x01\x12\x0e\n\nSTATE_IDLE\x10\x02"9\n\x06Struct\x12/\n\x06\x66ields\x18\x01'
    b' \x03(\x0b\x32\x1f.antigravity.localharness.Field"E\n\x05\x46ield\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12.\n\x05value\x18\x02'
    b' \x01(\x0b\x32\x1f.antigravity.localharness.Value"\xb7\x02\n\x05Value\x12\x39\n\nnull_value\x18\x01'
    b' \x01(\x0e\x32#.antigravity.localharness.NullValueH\x00\x12\x16\n\x0cnumber_value\x18\x02'
    b' \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x03'
    b' \x01(\tH\x00\x12\x14\n\nbool_value\x18\x04'
    b' \x01(\x08H\x00\x12\x38\n\x0cstruct_value\x18\x05 \x01(\x0b\x32'
    b' .antigravity.localharness.StructH\x00\x12\x39\n\nlist_value\x18\x06'
    b' \x01(\x0b\x32#.antigravity.localharness.ListValueH\x00\x12\x30\n\x05media\x18\x07'
    b' \x01(\x0b\x32\x1f.antigravity.localharness.MediaH\x00\x42\x06\n\x04kind"<\n\tListValue\x12/\n\x06values\x18\x01'
    b' \x03(\x0b\x32\x1f.antigravity.localharness.Value"q\n\x08ToolCall\x12\n\n\x02id\x18\x01'
    b' \x01(\t\x12\x0c\n\x04name\x18\x02'
    b' \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03'
    b' \x01(\t\x12\x33\n\targuments\x18\x04 \x01(\x0b\x32'
    b' .antigravity.localharness.Struct"\xa2\x01\n\x0cToolResponse\x12\n\n\x02id\x18\x01'
    b' \x01(\t\x12\x15\n\rresponse_json\x18\x02'
    b' \x01(\t\x12;\n\x12supplemental_media\x18\x03'
    b' \x03(\x0b\x32\x1f.antigravity.localharness.Media\x12\x32\n\x08response\x18\x04'
    b' \x01(\x0b\x32'
    b' .antigravity.localharness.Struct"\x8c\x02\n\x15UserQuestionsResponse\x12\x15\n\rtrajectory_id\x18\x01'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x02'
    b' \x01(\r\x12\x13\n\tcancelled\x18\x03'
    b' \x01(\x08H\x00\x12U\n\x08response\x18\x04'
    b' \x01(\x0b\x32\x41.antigravity.localharness.UserQuestionsResponse.QuestionsResponseH\x00\x1aR\n\x11QuestionsResponse\x12=\n\x07\x61nswers\x18\x01'
    b' \x03(\x0b\x32,.antigravity.localharness.UserQuestionAnswerB\x08\n\x06result"\x86\x01\n\x12UserQuestionAnswer\x12\x14\n\nunanswered\x18\x01'
    b' \x01(\x08H\x00\x12P\n\x16multiple_choice_answer\x18\x02'
    b' \x01(\x0b\x32..antigravity.localharness.MultipleChoiceAnswerH\x00\x42\x08\n\x06\x61nswer"R\n\x14MultipleChoiceAnswer\x12\x1f\n\x17selected_choice_indices\x18\x01'
    b' \x03(\x05\x12\x19\n\x11\x66reeform_response\x18\x02'
    b' \x01(\t"=\n\x05Media\x12\x11\n\tmime_type\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03'
    b' \x01(\x0c"\xa8\x01\n\rUsageMetadata\x12\x1a\n\x12prompt_token_count\x18\x01'
    b' \x01(\x05\x12"\n\x1a\x63\x61\x63hed_content_token_count\x18\x05'
    b' \x01(\x05\x12\x1e\n\x16\x63\x61ndidates_token_count\x18\x02'
    b' \x01(\x05\x12\x1c\n\x14thoughts_token_count\x18\x04'
    b' \x01(\x05\x12\x19\n\x11total_token_count\x18\x03'
    b' \x01(\x05*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x62\x08\x65\x64itionsp\xe9\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'localharness_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NULLVALUE']._serialized_start = 9017
  _globals['_NULLVALUE']._serialized_end = 9044
  _globals['_INPUTCONFIG']._serialized_start = 48
  _globals['_INPUTCONFIG']._serialized_end = 135
  _globals['_INITIALIZECONVERSATIONEVENT']._serialized_start = 137
  _globals['_INITIALIZECONVERSATIONEVENT']._serialized_end = 223
  _globals['_HARNESSCONFIG']._serialized_start = 226
  _globals['_HARNESSCONFIG']._serialized_end = 791
  _globals['_WORKSPACE']._serialized_start = 793
  _globals['_WORKSPACE']._serialized_end = 901
  _globals['_FILESYSTEMWORKSPACE']._serialized_start = 903
  _globals['_FILESYSTEMWORKSPACE']._serialized_end = 943
  _globals['_GEMINICONFIG']._serialized_start = 946
  _globals['_GEMINICONFIG']._serialized_end = 1115
  _globals['_GEMMACONFIG']._serialized_start = 1117
  _globals['_GEMMACONFIG']._serialized_end = 1168
  _globals['_SYSTEMINSTRUCTIONS']._serialized_start = 1171
  _globals['_SYSTEMINSTRUCTIONS']._serialized_end = 1343
  _globals['_CUSTOMSYSTEMINSTRUCTIONS']._serialized_start = 1346
  _globals['_CUSTOMSYSTEMINSTRUCTIONS']._serialized_end = 1475
  _globals['_CUSTOMSYSTEMINSTRUCTIONS_PART']._serialized_start = 1445
  _globals['_CUSTOMSYSTEMINSTRUCTIONS_PART']._serialized_end = 1475
  _globals['_APPENDEDSYSTEMINSTRUCTIONS']._serialized_start = 1478
  _globals['_APPENDEDSYSTEMINSTRUCTIONS']._serialized_end = 1663
  _globals['_APPENDEDSYSTEMINSTRUCTIONS_SECTION']._serialized_start = 1622
  _globals['_APPENDEDSYSTEMINSTRUCTIONS_SECTION']._serialized_end = 1663
  _globals['_TOOL']._serialized_start = 1665
  _globals['_TOOL']._serialized_end = 1768
  _globals['_HARNESSSIDETOOLS']._serialized_start = 1771
  _globals['_HARNESSSIDETOOLS']._serialized_end = 2522
  _globals['_FINDTOOLCONFIG']._serialized_start = 2524
  _globals['_FINDTOOLCONFIG']._serialized_end = 2563
  _globals['_RUNCOMMANDTOOLCONFIG']._serialized_start = 2565
  _globals['_RUNCOMMANDTOOLCONFIG']._serialized_end = 2610
  _globals['_SUBAGENTSCONFIG']._serialized_start = 2612
  _globals['_SUBAGENTSCONFIG']._serialized_end = 2652
  _globals['_USERQUESTIONSCONFIG']._serialized_start = 2654
  _globals['_USERQUESTIONSCONFIG']._serialized_end = 2698
  _globals['_FILEEDITTOOLCONFIG']._serialized_start = 2700
  _globals['_FILEEDITTOOLCONFIG']._serialized_end = 2743
  _globals['_VIEWFILETOOLCONFIG']._serialized_start = 2745
  _globals['_VIEWFILETOOLCONFIG']._serialized_end = 2788
  _globals['_WRITETOFILETOOLCONFIG']._serialized_start = 2790
  _globals['_WRITETOFILETOOLCONFIG']._serialized_end = 2836
  _globals['_GREPSEARCHTOOLCONFIG']._serialized_start = 2838
  _globals['_GREPSEARCHTOOLCONFIG']._serialized_end = 2883
  _globals['_LISTDIRTOOLCONFIG']._serialized_start = 2885
  _globals['_LISTDIRTOOLCONFIG']._serialized_end = 2927
  _globals['_GENERATEIMAGETOOLCONFIG']._serialized_start = 2929
  _globals['_GENERATEIMAGETOOLCONFIG']._serialized_end = 3029
  _globals['_PERMISSIONSCONFIG']._serialized_start = 3031
  _globals['_PERMISSIONSCONFIG']._serialized_end = 3088
  _globals['_OUTPUTCONFIG']._serialized_start = 3090
  _globals['_OUTPUTCONFIG']._serialized_end = 3135
  _globals['_OUTPUTEVENT']._serialized_start = 3138
  _globals['_OUTPUTEVENT']._serialized_end = 3470
  _globals['_STEPUPDATE']._serialized_start = 3473
  _globals['_STEPUPDATE']._serialized_end = 5080
  _globals['_STEPUPDATE_STATE']._serialized_start = 4790
  _globals['_STEPUPDATE_STATE']._serialized_end = 4899
  _globals['_STEPUPDATE_SOURCE']._serialized_start = 4901
  _globals['_STEPUPDATE_SOURCE']._serialized_end = 4987
  _globals['_STEPUPDATE_TARGET']._serialized_start = 4989
  _globals['_STEPUPDATE_TARGET']._serialized_end = 5080
  _globals['_ACTIONGENERATEIMAGE']._serialized_start = 5082
  _globals['_ACTIONGENERATEIMAGE']._serialized_end = 5160
  _globals['_ACTIONFINISH']._serialized_start = 5162
  _globals['_ACTIONFINISH']._serialized_end = 5199
  _globals['_ACTIONERROR']._serialized_start = 5201
  _globals['_ACTIONERROR']._serialized_end = 5256
  _globals['_ACTIONLISTDIRECTORY']._serialized_start = 5259
  _globals['_ACTIONLISTDIRECTORY']._serialized_end = 5452
  _globals['_ACTIONLISTDIRECTORY_RESULT']._serialized_start = 5377
  _globals['_ACTIONLISTDIRECTORY_RESULT']._serialized_end = 5452
  _globals['_ACTIONFINDFILE']._serialized_start = 5454
  _globals['_ACTIONFINDFILE']._serialized_end = 5525
  _globals['_ACTIONSEARCHDIRECTORY']._serialized_start = 5527
  _globals['_ACTIONSEARCHDIRECTORY']._serialized_end = 5610
  _globals['_ACTIONVIEWFILE']._serialized_start = 5612
  _globals['_ACTIONVIEWFILE']._serialized_end = 5685
  _globals['_ACTIONCREATEFILE']._serialized_start = 5687
  _globals['_ACTIONCREATEFILE']._serialized_end = 5742
  _globals['_ACTIONEDITFILE']._serialized_start = 5745
  _globals['_ACTIONEDITFILE']._serialized_end = 6187
  _globals['_ACTIONEDITFILE_DIFFLINE']._serialized_start = 5855
  _globals['_ACTIONEDITFILE_DIFFLINE']._serialized_end = 6070
  _globals['_ACTIONEDITFILE_DIFFLINE_LINEACTION']._serialized_start = 5959
  _globals['_ACTIONEDITFILE_DIFFLINE_LINEACTION']._serialized_end = 6070
  _globals['_ACTIONEDITFILE_DIFFBLOCK']._serialized_start = 6072
  _globals['_ACTIONEDITFILE_DIFFBLOCK']._serialized_end = 6187
  _globals['_ACTIONRUNCOMMAND']._serialized_start = 6189
  _globals['_ACTIONRUNCOMMAND']._serialized_end = 6294
  _globals['_ACTIONCOMPACTION']._serialized_start = 6296
  _globals['_ACTIONCOMPACTION']._serialized_end = 6314
  _globals['_ACTIONINVOKESUBAGENT']._serialized_start = 6316
  _globals['_ACTIONINVOKESUBAGENT']._serialized_end = 6338
  _globals['_TOOLCONFIRMATIONREQUEST']._serialized_start = 6340
  _globals['_TOOLCONFIRMATIONREQUEST']._serialized_end = 6365
  _globals['_USERQUESTIONSREQUEST']._serialized_start = 6367
  _globals['_USERQUESTIONSREQUEST']._serialized_end = 6448
  _globals['_USERQUESTION']._serialized_start = 6450
  _globals['_USERQUESTION']._serialized_end = 6550
  _globals['_MULTIPLECHOICE']._serialized_start = 6552
  _globals['_MULTIPLECHOICE']._serialized_end = 6628
  _globals['_INPUTEVENT']._serialized_start = 6631
  _globals['_INPUTEVENT']._serialized_end = 7010
  _globals['_USERINPUT']._serialized_start = 7013
  _globals['_USERINPUT']._serialized_end = 7236
  _globals['_USERINPUT_MEDIA']._serialized_start = 7083
  _globals['_USERINPUT_MEDIA']._serialized_end = 7144
  _globals['_USERINPUT_PART']._serialized_start = 7146
  _globals['_USERINPUT_PART']._serialized_end = 7236
  _globals['_TOOLCONFIRMATION']._serialized_start = 7238
  _globals['_TOOLCONFIRMATION']._serialized_end = 7317
  _globals['_TRAJECTORYSTATEUPDATE']._serialized_start = 7320
  _globals['_TRAJECTORYSTATEUPDATE']._serialized_end = 7503
  _globals['_TRAJECTORYSTATEUPDATE_STATE']._serialized_start = 7438
  _globals['_TRAJECTORYSTATEUPDATE_STATE']._serialized_end = 7503
  _globals['_STRUCT']._serialized_start = 7505
  _globals['_STRUCT']._serialized_end = 7562
  _globals['_FIELD']._serialized_start = 7564
  _globals['_FIELD']._serialized_end = 7633
  _globals['_VALUE']._serialized_start = 7636
  _globals['_VALUE']._serialized_end = 7947
  _globals['_LISTVALUE']._serialized_start = 7949
  _globals['_LISTVALUE']._serialized_end = 8009
  _globals['_TOOLCALL']._serialized_start = 8011
  _globals['_TOOLCALL']._serialized_end = 8124
  _globals['_TOOLRESPONSE']._serialized_start = 8127
  _globals['_TOOLRESPONSE']._serialized_end = 8289
  _globals['_USERQUESTIONSRESPONSE']._serialized_start = 8292
  _globals['_USERQUESTIONSRESPONSE']._serialized_end = 8560
  _globals['_USERQUESTIONSRESPONSE_QUESTIONSRESPONSE']._serialized_start = 8468
  _globals['_USERQUESTIONSRESPONSE_QUESTIONSRESPONSE']._serialized_end = 8550
  _globals['_USERQUESTIONANSWER']._serialized_start = 8563
  _globals['_USERQUESTIONANSWER']._serialized_end = 8697
  _globals['_MULTIPLECHOICEANSWER']._serialized_start = 8699
  _globals['_MULTIPLECHOICEANSWER']._serialized_end = 8781
  _globals['_MEDIA']._serialized_start = 7083
  _globals['_MEDIA']._serialized_end = 7144
  _globals['_USAGEMETADATA']._serialized_start = 8847
  _globals['_USAGEMETADATA']._serialized_end = 9015
# @@protoc_insertion_point(module_scope)
