apiVersion: v1
kind: Service
metadata:
  name: nanobot
  labels:
    app: nanobot
spec:
  selector:
    app: nanobot
  ports:
    - name: gateway
      port: 18790
      targetPort: 18790
      protocol: TCP
    - name: webui
      port: 8765
      targetPort: 8765
      protocol: TCP
