apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: goose-acpweb
  labels:
    app: goose-acpweb
spec:
  to:
    kind: Service
    name: goose-acpweb
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
