---
apiVersion: v1
kind: Secret
metadata:
  name: distribution-starter-secret
  labels:
    app: distribution-starter
type: Opaque
stringData:
  OPENAI_API_KEY: "REPLACE_WITH_API_KEY"
  OPENROUTER_API_KEY: "REPLACE_WITH_API_KEY"
  REDHAT_API_KEY: "REPLACE_WITH_API_KEY"
  ANTHROPIC_API_KEY: "REPLACE_WITH_API_KEY"
