apiVersion: v1
kind: ServiceAccount
metadata:
  name: pydantic-gateway
  labels:
    app: pydantic-gateway
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1",
      "reference":{"kind":"Route","name":"pydantic-gateway"}}
