apiVersion: v1
kind: Secret
metadata:
  name: pydantic-gateway-proxy-secret
  labels:
    app: pydantic-gateway
type: Opaque
stringData:
  # Generate with: openssl rand -base64 32
  session_secret: "<replace-with-openssl-rand--base64-32-output>"
