apiVersion: v1
kind: Secret
metadata:
  name: pi-ttyd-api-keys
  labels:
    app: pi-ttyd
type: Opaque
stringData:
  ANTHROPIC_API_KEY: "sk-ant-dummy"
  OPENAI_API_KEY: "<your-openai-api-key>"
  OPENROUTER_API_KEY: "sk-or-v1-dummy"
  GEMINI_API_KEY: "<your-gemini-api-key>"
