name: "Lightspeed Core Service (LCS)"
service:
  host: "0.0.0.0"
  port: 8080
  auth_enabled: false
  workers: 1
  color_log: true

conversation_cache:
  type: "sqlite"
  sqlite:
    db_path: "/tmp/data/conversations/lcs_cache.db"

user_data_collection:
  feedback_enabled: true
  feedback_storage: "/tmp/data/feedback"
  transcripts_enabled: true
  transcripts_storage: "/tmp/data/transcripts"
