[project]
name = "litellm-gw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "litellm[proxy]>=1.100.0",
    "openai>=2.54.0",
    "pydantic>=2.13.5",
    "uvicorn>=0.52.4",
]
