apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-workbench-agent-pvc
  labels:
    app: pi-workbench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
